### ISSUE TITLE
Project Planning

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#102]
### Issue Description

A project plan will be made using ProjectLibre tool. In order to do that, Yunus Emre, Muhammet Tayyip, and I will meet tomorrow at 12:00 and realize the project, then add it to our Wiki home page.

### Tasks

Parts of the task:
- [ ] Meet with team
- [ ] Realize the task
- [ ] Add it to wiki page

### Final Step

After finishing the task, we will add our project plan to our milestone report.

### Deadline of the Issue

10.04.2023 14.00

### Reviewer

@frknlke 

### Deadline for the Review

10.04.2023 18.00

**Comment by elifkizilky** [comment]
We made the project plan using ProjectLibre with my teammates. The work will be added to the wiki sidebar & milestone report.

**Comment by yunusemrealtug** [comment]
I have added to wiki page [here](https://github.com/bounswe/bounswe2023group7/wiki/Project-Plan). Not only reviewer but also everyone should check it and tell us. We worked yesterday based on issues and meeting notes. 

Issue needs review

**Comment by frknlke** [comment]
I reviewed the project plan and compared it with all the issues done so far. I did not encounter an error or omissions. Since @yunusemrealtug adviced all team members to check the project plan, I will not close the issue for couple of hours. If any team member finds an error or omission can freely state the missing part under this under this issue until that time.

**Comment by frknlke** [comment]
Since there is no extra comment, I will close the issue.
