### ISSUE TITLE
Individual Report & RAM contributions part- Elif Kızılkaya

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#104]
### Issue Description

An individual report regarding my contributions to our project will be written according to the specifications given by the lecture and will be added to our repository & milestone report. Also, the parts that I contributed will be filled in RAM.

### Tasks

Parts of the task:
- [x] write invidiual report
- [x] add it to wiki
- [x] add it to milestone report
- [x] Fill contributions in RAM

### Deadline of the Issue

10.04.2023 14.00

### Reviewer

@omersafakbebek 

### Deadline for the Review

10.04.2023 18.00

**Comment by elifkizilky** [comment]
I filled my individual contributions report according to the template prepared and it can be seen by this [link](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-(Elif-K%C4%B1z%C4%B1lkaya)). Now, the work needs review.
