### ISSUE TITLE
Individual Report - Muhammet Tayyip Kamiloğlu

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#106]
### Issue Description

As we discussed in the 7th meeting, I will write a personal report summarizing our contributions to the project. Afterward, I will fill in the Ram table once I add it to Github.

### Tasks

Parts of the task:
- [x] Write the report
- [x] Add it to the github
- [x] Add it to the milestone report
- [x] Fill the RAM table

### Deadline of the Issue

10.04.2023 - Monday - 14.00

### Reviewer

@omersafakbebek 

### Deadline for the Review

10.04.2023 - Monday - 16.00

**Comment by omersafakbebek** [comment]
Individual contributions report of @mtkamiloglu has been reviewed. The task is done.
