### ISSUE TITLE
Milestone Report - Executive Summary

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#107]
### Issue Description

I will write a summary about our project. This summary includes project status and any changes in plans based on reflections.

### Tasks

Parts of the task:
- [x] Write Introduction/Project Description
- [x] Write Project Status
- [x] Write forward plan
- [ ] Add these to the milestone report

### Deadline of the Issue

10.04.2023 - Monday - 14.00

### Reviewer

@Hakkush-07 

### Deadline for the Review

10.04.2023 - Monday - 16.00

**Comment by mtkamiloglu** [comment]
All parts of the summary is written, it can be reviewed and closed
