### ISSUE TITLE
Individual Report - Güney Yüksel

### ISSUE THREAD

**Issue by SouthAscend** [bounswe/bounswe2023group7#113]
### Issue Description

Per our decisions on Meeting 7, I will complete my individual report on my part on this repository and my part of the RAM.

### Tasks

Parts of the task:
- [x] Complete the individual report
- [x] Add it to GitHub
- [x] Add it to Milestone Report
- [x] Fill the RAM table

### Deadline of the Issue

10.04.2023

### Reviewer

@frknlke 

### Deadline for the Review

10.04.2023

**Comment by SouthAscend** [comment]
I've added my [Individual Contribution Report](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-(Güney-Yüksel)) to the wiki pages.

**Comment by frknlke** [comment]
I inspected the report. I did not encounter an erroneous or missing part. I will close the issue.
