### ISSUE TITLE
Individual Report - Furkan Ülke

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#114]
### Issue Description

As we decided on Meeting 7, I will complete my individual report on my part on this repository and my part of the RAM.

### Tasks

Parts of the task:
- [x] Complete the individual report
- [x] Add it to GitHub
- [x] Add it to Milestone Report
- [x] Fill the RAM table

### Extra Comments

_No Response_

### Final Step

_No Response_

### Deadline of the Issue

10.04.2023 - Monday - 12:00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

10.04.2023 - Monday - 18:00

**Comment by frknlke** [comment]
I've added my [Individual Contribution Report](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-(Furkan-Ülke)) to the wiki pages. Review is needed.

**Comment by yunusemrealtug** [comment]
You can review your management issue but it is not necesary, I am closing.
