### ISSUE TITLE
Revision of RAM

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#120]
### Issue Description

RAM will be checked and added to the milestone report.

### Tasks

Parts of the task:
- [x] Finish the RAM completely 
- [x] Add it to the report
- [x] Add new tasks to the RAM

### Deadline of the Issue

10.04.2023

### Reviewer

@SouthAscend 

### Deadline for the Review

10.04.2023

**Comment by SouthAscend** [comment]
Issues, meetings and roles were listed succesfully.
