### ISSUE TITLE
Individual Report - Mehmet Tuluyhan Sözen

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#122]
### Issue Description

I need to prepare individual report

### Tasks

Parts of the task:
- [x]  Complete the individual report
- [x]  Add it to GitHub
- [x] Fill the RAM table

### Deadline of the Issue

10.04.2023

### Reviewer

@elifkizilky 

### Deadline for the Review

10.04.2023

**Comment by elifkizilky** [comment]
The links for the issues should be added, the Name Surname part should be added, and you can clear the definitions for the parts that are written between <>.  You can name the page "Individual Contribution Report (Mehmet Tuluyhan Sözen)" for name coherency as well.

**Comment by elifkizilky** [comment]
The work is done and issue can be closed.
