### ISSUE TITLE
Individual Report & RAM Contributions Yunus Emre Altuğ

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#123]
### Issue Description

An individual report regarding my contributions to our project will be added for milestone. Also, I must check and add contributions to RAM.

### Tasks

Parts of the task:
- [x] write invidiual report
- [x] add it to wiki
- [x] Fill contributions in RAM

### Deadline of the Issue

10.04.2023 - Monday - 11.00

### Reviewer

@mtkamiloglu  

### Deadline for the Review

10.04.2023 - Monday - 18.00

**Comment by yunusemrealtug** [comment]
I will add individual report to milestone later, so I remove adding it to report task from the issue. Individual report can be reviewed now from [here](https://github.com/bounswe/bounswe2023group7/wiki/Individual-Contribution-Report-(Yunus-Emre-Altu%C4%9F)).

**Comment by mtkamiloglu** [comment]
I reviewed the page. It is well done. I am closing the issue
