### ISSUE TITLE
Individual Report & RAM Contributions Melih Gezer

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#129]
### Issue Description

An individual report regarding my contributions to our project will be added for milestone. Also, I must check and add contributions to RAM.

### Tasks

Parts of the task:
- [x] write invidiual report
- [x] add it to wiki
- [x] Fill contributions in RAM

### Deadline of the Issue

10.04.2023

### Reviewer

@senaal 

### Deadline for the Review

10.04.2023

**Comment by senaal** [comment]
The task is done.
