### ISSUE TITLE
Establishing the database connection for the practice app

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#151]
### Issue Description

As we talked in meeting 9, I will write the codes for establishment of the database connection.

### Tasks

Parts of the task:
- [x] Creating new branch for the task
- [x] Write the codes
- [x] Test whether the code works
- [x] Push the codes to the opened branch and create a pull request

### Deadline of the Issue

08.05.2023-13.00

### Reviewer

@melihgezerr 

### Deadline for the Review

08.05.2023-23.59

**Comment by omersafakbebek** [comment]
The task is completed and can be reviewed through [#152](https://github.com/bounswe/bounswe2023group7/pull/152).
