### ISSUE TITLE
Adding swagger documentation functionality to the practice app.

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#153]
### Issue Description

As we talked in meeting 9, I will add the swagger documentation functionality to the practice app.

### Tasks

Parts of the task:
- [x] Creating new branch for the task
- [x] Preparing swagger environment for documentation and swagger-ui
- [x] Adding an example api documentation
- [x] Pushing the changes to the created branch and creating a pull-request

### Deadline of the Issue

08.05.2023-13.00

### Reviewer

@elifkizilky 

### Deadline for the Review

08.05.2023-23.59

**Comment by omersafakbebek** [comment]
Parts of the task is completed and can be reviewed through [#154](https://github.com/bounswe/bounswe2023group7/pull/154).
