### ISSUE TITLE
Adding jest configuration to the practice app

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#155]
### Issue Description

As we talked in meeting 9, I will add the jest configuration to the practice app. Jest will be used for unit testing.

### Tasks

Parts of the task:
- [x] Creating a new branch for the task
- [x] Adding jest config file
- [x] Preparing an example unit test
- [x] Pushing the changes to the created branch and creating a pull request

### Deadline of the Issue

08.05.2023-13.00

### Reviewer

@frknlke 

### Deadline for the Review

08.05.2023-23.59

**Comment by omersafakbebek** [comment]
All parts of the task are completed. The work done can be reviewed through [#156].
