### ISSUE TITLE
Adding favorite games feature to the practice-app

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#157]
### Issue Description

As a requirement of the practice-app, each of us should consume at least one api call and provide at least one api function. I decided on a favorite games system that uses [Internal Steam Web API](https://github.com/Revadike/InternalSteamWebAPI). The end user will search a string in the steam apps and get a list. The user will choose one of the games and the chosen game (with an identifier of the user)  will be added to our database. When the end user wants to see its favorite games, the favorite games will be listed. 

### Tasks

Parts of the task:
- [x] Creating a new branch for the task
- [x] Creating search api function
- [x] Creating  add to favorites api function
- [x] Creating remove from favorites api function
- [x] Creating get favorites api function
- [x] Testing the api functions with Postman
- [x] Adding documentations of the written api functions (with swagger)
- [x] Creating unit tests for the api functions (with jest)
- [x] Pushing the api functions to the created branch and creating a new pull request

### Final Step

Interface for the feature will be created.
### Deadline of the Issue

08.05.2023-17.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

08.05.2023-23.59

**Comment by omersafakbebek** [comment]
The parts of the task are completed but it is needed to change some logic after the completion of [#168](https://github.com/bounswe/bounswe2023group7/issues/168).

**Comment by omersafakbebek** [comment]
The work can be reviewed through [#184](https://github.com/bounswe/bounswe2023group7/pull/184).
