### ISSUE TITLE
Adding Location History Feature to Practice App

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#158]
## Task

I investigated APIs and found one to consume an API call result and create an API function. I will utilize [IP Geolocation API](https://www.abstractapi.com/api/ip-geolocation-api). Whenever the user enters the site, his/her location is saved to history. My functionalities are:
-  Finding the location of the user using the IP address and letting the user see whenever s/he wants to see his/her location
- Adding his/her location to the database and letting the user see his/her location history whenever the user wants.

I will provide city, country, postal code, region, country flag, and time data. (*)

## Views

The feature will have the following views:

1.  User clicks on the "Where Am I?" button and sees his/her current location with the provided data (*)
2. User clicks on "My Location History" and sees his/her location history.
3.  On the main page, there will be a button page navigating to a page containing (1) and (2) buttons

## Endpoints

The views will be utilizing the following endpoints:

1. The `addLocation` is a `POST` method that adds the location of the user to the location history
2. The `getLocationHistory` is a `GET` method that returns the location history of the user
3.  The `findLocation` is a `GET` method that returns the current location of the user

## Model

To store the location of the user, I will create a `location` schema following the corresponding columns:

-  `email` is the email of the user
- `city` is the city data provided by API according to the IP address
- `country` is the country data provided by API according to IP address
- `region` is the region data provided by API according to IP address
- `postal code`  is the postal code data provided by API according to the IP address
- `country flag` is the country flag data provided by API according to the IP address
- `time` is the time data provided by API according to the IP address
- `currency` is the currency data provided by API according to IP address

## Tests

All functionalities will be tested

## Swagger Documentation

I will provide Swagger documentation for the routes.

### Tasks

Parts of the task:
- [x] Creating a new branch for the task
- [x]  Create `addLocation ` method
- [x] Create `getLocation` method
- [x] Create `getLocationHistory`
- [x]  Testing the api functions with Postman
- [x]  Adding documentations of the written api functions (with swagger)
- [x]  Creating unit tests for the api functions (with jest)
- [x]  Pushing the api functions to the created branch and creating a new pull request

 

### Final Step

After finishing my tasks, I will create pull request and push all my work

### Deadline of the Issue

08.05.2023 23:59

### Reviewer

@omersafakbebek 

### Deadline for the Review

09.05.2023 23:59

**Comment by elifkizilky** [comment]
The task is implemented and pull request is done. Issue needs review

**Comment by omersafakbebek** [comment]
I checked the api functions. Everything seems fine. I tried the api functions by using the application. There is no problem. I checked the unit tests. They test an enough number of cases. Good Work!
