### ISSUE TITLE
Giving Information About Game Platform Feature to Practice API

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#159]
## Task

I searched about api's which related to our project, and I found out moby games, which gives user much information about many games. The planned functionalities are:

- User should be able to search and click game which user learn its platforms. (ex. Playstation 5, MS Windows, Xbox One X...)
- Database should keep the user's platform.

## Endpoints

The views will be utilizing the following endpoints:

1. The `addPlatform` is a `POST` method that adds user's platform information to database.
2. The `searchGames` is a `GET` method that displays searched games by keyword.
3.  The `getPlatforms` is a `GET` method that returns the platforms of the game.

## Tests

All functionalities will be tested

## Swagger Documentation

I will provide Swagger documentation for the routes.

### Tasks

Parts of the task:
- [x] Creating a new branch for the task
- [x]  Create `addPlatform` method
- [x] Create `searchGames` method
- [x] Create `getPlatforms`
- [x]  Testing the api functions with Postman
- [x]  Adding documentations of the written api functions (with swagger)
- [x]  Creating unit tests for the api functions (with jest)
- [ ]  Pushing the api functions to the created branch and creating a new pull request

### Deadline of the Issue

10.05.2023 - Wednesday - 11.00

### Reviewer

@mtkamiloglu 

### Deadline for the Review

10.05.2023 - Wednesday - 23:59

**Comment by yunusemrealtug** [comment]
I actually have written most parts of the code but we decided to add login sign in system to whole practice api so, I will update these part later.

**Comment by yunusemrealtug** [comment]
The desirable part does not make sense now for me. Therefore, I am removing it from tasks and whole issue.

**Comment by mtkamiloglu** [comment]
I reviewed the code and merged with main branch. I am closing the issue
