### ISSUE TITLE
Create addLocation, getLocationHistory, and findLocation Endpoints for API

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#162]
### Issue Description

As described at #158, I will add the following endpoints:
- `AddLocation `endpoint will add the user's location to the database according to e-mail and ip_address.
- `getLocationHistory` endpoint will show the user's location history according to e-mail.
- `findLocation ` endpoint will show the user's current location according to email and ip_address.

### Tasks

Parts of the task:
- [x] Add `addLocation` function to the location controller file
- [x]  Add `getLocationHistory` function to the location controller file
- [x] Add `findLocation` function to the location controller file
- [x] Create location route file accordingly
- [x] Test them using Postman

### Final Step

When I complete my work, I will create a pull request for review.

### Deadline of the Issue

09.05.2023 23.59

### Reviewer

@frknlke 

### Deadline for the Review

10.05.2023 23:59

**Comment by elifkizilky** [comment]
The task is implemented and pull request is done. Issue needs review

**Comment by frknlke** [comment]
I tested all endpoints created. Everything works just fine and code is merged to the main. Closing the issue.
