### ISSUE TITLE
API Function

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#166]
### Issue Description

I decided RAWG API and I will find genres and game counts. 

### Tasks

Parts of the task:
- [ ] Test Api at Postman.
- [ ] Clone main project from GitHub.
- [ ] Write controller.js.
- [ ] Write model.js.
- [ ] Write routes.js.
- [ ] Write test.js.

### Deadline of the Issue

10,05.2023

### Reviewer

@safa
