### ISSUE TITLE
API Function

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#167]
### Issue Description

I decided RAWG API and I will find genres and game counts. 

### Tasks

Parts of the task:
- [x] Test Api at Postman.
- [x] Clone main project from GitHub.
- [x] Write controller.js.
- [x] Write model.js.
- [x] Write routes.js.
- [x] Write test.js.

### Deadline of the Issue

10,05.2023

### Reviewer

@omersafakbebek

**Comment by senaal** [comment]
It is done and needs review. @omersafakbebek

**Comment by omersafakbebek** [comment]
I checked the code, there are 3 api functions. The first one gets all genres from the api. The second one adds the all genres to our database with an additional info which is email. The third one gets all genres from the database with given email. These api functions does what it aims to do. But when I tried the second function twice, the app crashes due to uniqueness of genre.
