### ISSUE TITLE
Adding signup and login structure to the backend of practice-app

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#168]
### Issue Description

As we talked in the meeting on May 8th, I will add signup and login structure to the backend of practice app. This structure will generate a jwt token for the user who wants to login.

### Tasks

Parts of the task:
- [ ] Creating a new branch for the task
- [ ] Creating user model
- [ ] Creating signup endpoint
- [ ] Creating login endpoint
- [ ] Creating  middlewares for authorization
- [ ] Testing the endpoints on postman
- [ ] Creating swagger docs for  the endpoints
- [ ] Creating unit tests for the endpoints
- [ ] Pushing the changes to the created branch and creating a new pull request

### Final Step

After finishing the task, I will change my api functions (which is being handled in [#157](https://github.com/bounswe/bounswe2023group7/issues/157)) to use this structure and inform my teammates.

### Deadline of the Issue

10.05.2023-14.00

### Reviewer

@yu

### Deadline for the Review

10.05.2023-Monday-23.59

**Comment by omersafakbebek** [comment]
I completed the parts of the task. The work can be reviewed through [#169](https://github.com/bounswe/bounswe2023group7/pull/169).

**Comment by yunusemrealtug** [comment]
As I reviewed in pull request, program does what it aims. Thanks for the effort.
