### ISSUE TITLE
Frontend Landing Page 

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#185]
### Issue Description

There should be a landing page that navigates to our individual works by buttons. This page should have a welcome text, brief information about our group, a sidebar, and a header. 

### Tasks

Parts of the task:
- [x] Create landing page
- [x] add header
- [x] add sidebar
- [x] add buttons
- [x] add welcome text 
- [x] add links to our repository for more information about our group

### Final Step

After finishing this task, I will add my work to our repository and create a pull request.

### Deadline of the Issue

10.05.2023 23:59

### Reviewer

@omersafakbebek 

### Deadline for the Review

11.05.2023 23:59

**Comment by elifkizilky** [comment]
Using React, I created a landing page with a simple user interface. This page includes a header: it includes a sidebar that includes contributors' name and their links to GitHub.  I added buttons that navigate to the pages that my teammates will create for their API.

**Comment by omersafakbebek** [comment]
The pull request is merged.
