### ISSUE TITLE
Frontend of Genre API

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#190]
### Issue Description

When backend part is completely done, I will implement frontend part of my API using React.js.

### Tasks

Parts of the task:
- [x] Creating client folder.
- [x] Implement frontend part.
- [x] Merge with main code. 

### Deadline of the Issue

12.05.2023 12.00

### Reviewer

@melihgezerr 

### Deadline for the Review

12.05.2023

**Comment by senaal** [comment]
The frontend part is completed and merged to the main. This issue needs review. @melihgezerr

**Comment by melihgezerr** [comment]
This looks good, ı am closing it.
