### ISSUE TITLE
Login and Signup pages with backend integration for practice app

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#191]
### Issue Description

I will create login and signup pages in our frontend and integrate these pages with our backend.

### Tasks

Parts of the task:
- [x] Creating a new branch for the task
- [x] Creating signup page
- [x] Integrating the signup page with backend
- [x] Creating login page
- [x] Integrating the login page with backend
- [x] Creating logout button and its effect
- [x] Pushing the changes to the created branch and creating a pull request

### Deadline of the Issue

11.05.2023-17.00

### Reviewer

@elifkizilky 

### Deadline for the Review

11.05.2023-23.59
