### ISSUE TITLE
Frontend of Favorite Games feature

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#192]
### Issue Description

I will create a page on which the user can search games and add games to his/her favorite games. The user also can see his/her favorite games on this page.

### Tasks

Parts of the task:
- [x] Creating a new branch for the task
- [x] Creating the favorite games page
- [x] Integrating the page with our backend
- [x] Pushing the changes to the created branch and creating a pull request

### Deadline of the Issue

11.05.2023-23.59

### Reviewer

@tuluyhansozen 

### Deadline for the Review

12.05.2023-17.00

**Comment by omersafakbebek** [comment]
I added favorite games page to our application. A logged in user can search games, add them to his/her favorites by clicking them. Also the user can see his/her favorite games and remove games from the list by clicking them. The work can be reviewed through #202.
