### ISSUE TITLE
Frontend of Game Prices Feature

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#193]
### Issue Description

I will create a page on which the user can search for game prices and add games to his/her cart with the lowest price. The user also can see his/her cart and game stores available in the market.

### Tasks

Parts of the task:
 - [x] Creating a new branch for the task
 - [x] Creating the game prices page
 - [x] Integrating the page with our backend
 - [x] Pushing the changes to the created branch and creating a pull request

### Deadline of the Issue

12.05.2023 02:00

### Reviewer

@omersafakbebek 

### Deadline for the Review

12.05.2023 - 16.00
