### ISSUE TITLE
Adding Event Location Feature to Practice App

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#195]
### Task
I searched for APIs and found one that I think it would be useful for the app.  I will utilize [Geocoding API](https://developers.google.com/maps/documentation/geocoding/overview). When user requests to create an event, it required to provide some information, such name, date, time, and location of the event. So whenever user provides these, its address will be converted to longitude and latitude format and saved to history. My functionalities are:

- Finding the corresponding coordinate address of the event.
- Adding the event to database with coordinate address and letting the user see list of created events whenever user wants.

### Endpoints
I will utilize the following endpoints

- `events/list` is a `GET` method that returns all the events created so far.
- `events/createEvent` is a `POST` method that creates a new event with provided informations.

### Model
To store the events, I will create a `event` schema following the corresponding columns:

- `eventName` is the name of the event
- `eventDate` is the date of the event with `year`, `month`, and `day` subfields.
- `eventTime` is the planned time of the event represented with an string that has the format `HH:MM` or `HH.MM`.
- `eventLocationLatitude` is the latitude axis value for the coordinate address.
- `eventLocationLongitude` is the longitude axis value for coordinate address.

### Tests
All functionalities will be tested.

### Swagger Documentation
I will provide swagger documentation for the routes.

### Tasks

Parts of the task:
- [x] Create a new branch for the task
- [x] Create methods for `createEvent` endpoint.
- [x] Create methods for `events/list` endpoint.
- [x] Testing the API function with Postman
- [x] Adding swagger documentations
- [x] Creating unit test unit test for the api functions
- [x] Pushing the api functions to the branch and create a new pull request.

### Final Step

After finishing the task, I will create a pull request.

### Deadline of the Issue

12.05.2023 - 12:00

### Reviewer

@yunusemrealtug

### Deadline for the Review

12.05.2023 - 20:00

**Comment by frknlke** [comment]
I did all todos and my [pull request](https://github.com/bounswe/bounswe2023group7/pull/218) accepted. Thus I am closing the issue.
