### ISSUE TITLE
Frontend of EventLocation Feature

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#197]
### Issue Description

I will create a page where user can create an event or list events created so far.

### Tasks

Parts of the task:
- [x] Creating a new branch for the task.
- [x] Creating the events page.
- [x] Integrating the page with our backend
- [x] Pushing the changes to the created branch and creating a pull request

### Deadline of the Issue

12.005.2023 - 18:00

### Reviewer

@omersafakbebek

### Deadline for the Review

12.05.2023 - 21:00

**Comment by frknlke** [comment]
I created my frontend pages and integrated them with my backend functions. At final, I did [a pull pull request](https://github.com/bounswe/bounswe2023group7/pull/218) and my code merged with main.
