### ISSUE TITLE
Front-end Page for Location Apı

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#198]
### Issue Description

As described in #158 , I will be doing the frontend page of my functionalities. There will be "Find Location" button where user can see his/her location when click on it. And also there will be "Get My Location History" button where the user can see his/her location history when click on it. Also, there wlil be "Add Location to History" button where user clicks on it, the location of the user will be added to his/her history.

### Tasks

Parts of the task:
- [x] Implement the "Find Location" button 
- [x] Implement the "Get My Location History" button
- [x] Implement the "Add Location to History" button

### Deadline of the Issue

12.05.2023 17:00

### Deadline for the Review

12.05.2023 23:59

**Comment by elifkizilky** [comment]
The task is implemented and pull request is done. Issue needs review

**Comment by elifkizilky** [comment]
The task is implemented and pull request is done. Issue needs review

**Comment by melihgezerr** [comment]
Since there is no reviewer assigned to this issue, I am closing it as done.
