### ISSUE TITLE
Fatma Sena Alçı Indıvıdual Report

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#203]
### Issue Description

I will create individual report page for my contributions for second milestone. 

### Tasks

Parts of the task:
- [x] Creation of individual report page
- [x] Explaining my API and my functions
- [x] Describing any challenges I met

### Deadline of the Issue

12,05.2023

**Comment by senaal** [comment]
The task is done.
