### ISSUE TITLE
Meeting 2 Notes 

### ISSUE THREAD

**Issue by tuluyhansozen** [bounswe/bounswe2023group7#21]
### Issue Description

Taking and uploading notes of the second meeting. 

### Tasks

Parts of the task:
- [ ] Taking notes of the second meeting.
- [ ] Summarizing second meeting's notes
- [ ] Uploading second meeting's notes

### Deadline of the Issue

12.03.2023

### Reviewer

Hakan Karakus

### Deadline for the Review

14.03.2023

**Comment by Hakkush-07** [comment]
Meeting 2 Note is completed [here](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-Notes-%232-(10.03.2023)) and added to home page
