### ISSUE TITLE
Random Game API

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#212]
### Task
I will use Steam API to fetch random game from its library. I thought it will be nice to have function to suggest a random game. I am inspired by XBOX Game Pass suggestion feature. My API will send request to the public API (https://api.steampowered.com/ISteamApps/GetAppList/v2/). It will send a JSON object and my API will choose a random game from this object. And another function will add this game to the database. My functionalities are:

- Returning a random game to the user and adding this game to the user's history. 
- Returning the random game history of the user from database.

### Endpoints
I will utilize the following endpoints

- `/random-game` is a `POST` method that returns a random game from Steam library and adds it to the database.
- `/random-game/history` is a `GET` method that returns random game history of the user.

### Model
To store the random games, I will create a `randomGame` schema following the corresponding columns:

- `appId` is the id of the game on Steam
- `name` is the name of the random game
- `shortDescription` is a string short description of the game.
- `headerImage` is the link to the image of the game.
- `price` is the price of the game. It is stored as a string
- `email` is the email of the user. 

### Tests
I will test get and post method. 

### Swagger Documentation
I will provide swagger documentation for the routes.

### Tasks

Parts of the task:
- [x] Create a new branch for the task
- [x] Create methods for `/random-game` endpoint.
- [x] Create methods for `/random-game/history` endpoint.
- [x] Testing the API function with Postman
- [x] Adding swagger documentations
- [x] Creating unit test unit test for the api functions
- [ ] Pushing the api functions to the branch and create a new pull request.

### Final Step

After finishing the task, I will create a pull request.

### Deadline of the Issue

12.05.2023 - 12:00

### Deadline for the Review

12.05.2023 - 20:00

**Comment by mtkamiloglu** [comment]
I created the public API and it's deployed to AWS server. It works correctly. I am closing the issue.
