### ISSUE TITLE
Deciding technologies to be used in the implementation for back-end

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#238]
### Issue Description

Before the implementation phase of our project, the back-end team should decide on which technologies to use with careful discussion. 

### Tasks

Parts of the task:
- [x] Discussing which technologies team members already have experience with.
- [x] Discussing the advantages and disadvantages of the technologies and their compatibility with our project.
- [x] Finalize the decision

### Extra Comments

Related team members can address their opinions under this issue and we can discuss it collaboratively.

### Final Step

The decision will be made and we can add it to the documentation of the project.

### Deadline of the Issue

10.10.2023 - 15.00

**Comment by omersafakbebek** [comment]
I recommend using Node.js for its performance (also we have experience in Node.js from the practice app), NestJS framework for structured development (has good features like decorators for dependency injection), TypeScript for type safety, and PostgreSQL for a reliable database. These technologies complement each other well and are widely used in the industry, providing a strong foundation for our project.

**Comment by melihgezerr** [comment]
We decided to use nodejs, nestjs, typescript ve postgresql for our backend part.
