### ISSUE TITLE
Deciding technologies to be used in the implementation for front-end

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#239]
### Issue Description

Before the implementation phase of our project, the front-end team should decide on which technologies to use with careful discussion.

### Tasks

Parts of the task:
- [ ]  Discussing which technologies team members already have experience with.
- [ ]  Discussing the advantages and disadvantages of the technologies and their compatibility with our project.
- [ ]  Finalize the decision.

### Extra Comments

Related team members can address their opinions under this issue and we can discuss it collaboratively.

### Final Step

The decision will be made and we can add it to the documentation of the project.

### Deadline of the Issue

10.10.2023 - 15.00

**Comment by yunusemrealtug** [comment]
react.js is good option to use. I have no doubt that it is sufficient to handle interface and i have encountered in my internship which proves its productivity. Also, I believe going forward would be faster.

**Comment by mtkamiloglu** [comment]
I also think it would be easier to write and learn React. But it might also be good to do some research on next.js

**Comment by elifkizilky** [comment]
I agree with you. I have done some research on Next.js. The distinction of Next.js is that it extends React to include server-side rendering and static site generation. I think React could be sufficient for our needs. Also, we have more experience with React.

**Comment by mtkamiloglu** [comment]
After discussions both here and through other communication channels, we decided on **React**. So I am closing this issue.
