### ISSUE TITLE
Deciding technologies to be used in the implementation for mobile

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#240]
### Issue Description

Before the implementation phase of our project, the mobile team should decide on which technologies to use with careful discussion.

### Tasks

Parts of the task:
- [x] Discussing which technologies team members already have experience with.
- [x] Discussing the advantages and disadvantages of the technologies and their compatibility with our project.
- [x] Finalize the decision.

### Extra Comments

Related team members can address their opinions under this issue and we can discuss it collaboratively.

### Final Step

The decision will be made and we can add it to the documentation of the project.

### Deadline of the Issue

10.10.2023 - 15.00

**Comment by haticerk** [comment]
I think we should consider Java and React Native.

**Comment by frknlke** [comment]
Flutter's main advantages can be listed as following:

- It includes hot restart and a well-regarded “hot reload” function, which allows you to see updates in real time without restarting the app.
- Everything in Flutter can be built from widgets and there are lots of ready-made as well as customizable ones.
- Since Flutter doesn’t use a bridge for communication between the app and the platform you get a faster-starting app with beautiful, fast animations and fewer performance problems.
- It's an open-source platform and it has an engaged community.

**Comment by kardelenerdal** [comment]
I also suggest using Flutter for our mobile app. I guess we can build the app for both iPhone and Android at the same time with Flutter. And the hot reload function is great considering we'll be making constant changes throughout the semester.

**Comment by haticerk** [comment]
The final decision is the **Flutter** then. Let's close the issue.
