### ISSUE TITLE
Revising class diagram from previous semester

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#241]
### Issue Description

We got feedback about our project requirements with our customer assistant at the latest lab section. We will revise the [class diagram](https://github.com/bounswe/bounswe2023group7/wiki/Class-Diagrams) that we made in the previous semester accordingly. We will convert it to a diagram that is more game-specific and discuss our design. 

### Tasks

Parts of the task:
- [x] Hold a meeting with the team.
- [x] Discuss the design of the project.
- [ ] Update the class diagram.

### Final Step

New class diagram should be put on the wiki page.

### Deadline of the Issue

10.10.2023 - 13.00

### Reviewer

@omersafakbebek 

### Deadline for the Review

10.10.2023 - 15.00

**Comment by elifkizilky** [comment]
We completed the revision of the class diagram: we updated the game class; and added entity, system requirements, board game, and video games classes. We also added entity types and video game types as enumeration. You can access the work from the [link](https://lucid.app/lucidchart/9e8874f9-af13-4a27-babc-9050045dc765/edit?invitationId=inv_5b542f94-3579-4d0b-9948-dd18e9061c41&page=HWEp-vi-RSFO#).
![UML class (2)](https://github.com/bounswe/bounswe2023group7/assets/69367633/cb8211ed-feef-4c01-a5f1-4ba89db6d25b)

**Comment by omersafakbebek** [comment]
I reviewed the task. The class diagram has been revised according to the new project requirements. The task has been completed.
