### ISSUE TITLE
Revising requirements from previous semester

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#242]
### Issue Description

We got feedback about our project requirements with our customer assistant at the latest lab section. We will revise the [requirements](https://github.com/bounswe/bounswe2023group7/wiki/Requirements) that we prepared in the previous semester accordingly. We will convert them so that are more game-specific and discuss our design.

### Tasks

Parts of the task:
- [x]  Hold a meeting with the team.
- [x] Discuss the design of the project.
- [x] Update the requirements.

### Final Step

New requirements should be put on the wiki page.

### Deadline of the Issue

10.10.2023 - 13.00

### Reviewer

@elifkizilky 

### Deadline for the Review

10.10.2023 - 15.00

**Comment by yunusemrealtug** [comment]
is updating diagram part of the issue?

**Comment by elifkizilky** [comment]
It should be "requirements", my mistake 😸 :

**Comment by yunusemrealtug** [comment]
We have updated requirements. Some new feature are added and the requirement structure constructed again. Also, due to the fact that I am the one of the assignees, I modified the reviewer as @elifkizilky. Would you review it.

**Comment by elifkizilky** [comment]
I checked the requirements, everything is nicely done. I just noticed that we can add the definitions for,

-  entity,
-  character, 
- environment,
- package,
- item 

to the glossary.

**Comment by yunusemrealtug** [comment]
I added them.

**Comment by elifkizilky** [comment]
Requirements are revised and reviewed. Issue can be closed.
