### ISSUE TITLE
Revising event and group requirements

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#248]
### Issue Description

We will meet as a team and talk about our event and group design. The main issues are:

- Making them more game-specific
- Integrating them according to new features we added

### Tasks

Parts of the task:
- [x] Hold the meeting
- [x] Discuss the event and group design
- [x] Update the requirements accordingly

### Deadline of the Issue

17.10.2023

### Reviewer

@melihgezerr
