### ISSUE TITLE
Mock-Up Design

### ISSUE THREAD

**Issue by melihgezerr** [bounswe/bounswe2023group7#26]
### Issue Description

For this week's task, we should make mock-ups for our project and think about use cases to present how our requirements could satisfy the project owner

### Tasks

Parts of the task:
- [x] Decide on a suitable mock-up tool
- [x] Meet with the mock-up team members
- [x] Realize the task
- [x] Add the task to our wiki page

### Deadline of the Issue

20.03.2023 - Monday - 23.59

### Reviewer

@senaa

### Deadline for the Review

22.03.2023

**Comment by melihgezerr** [comment]
@senaal  I misspelled your username for the reviewer.

**Comment by elifkizilky** [comment]
I opened issue #40  and shared a link for mock-up tools, please check it.

**Comment by elifkizilky** [comment]
We chose Figma as Mock-Up design tool.

**Comment by elifkizilky** [comment]
Home Page Mock-Up is done, you can access from it [here](https://www.figma.com/file/ys7rBkkB4wAThXJVYEscff/Home-Page?node-id=0%3A1&t=3KqdqV7BL2KElmdo-1).

**Comment by melihgezerr** [comment]
Also you can find the mock-up page on [here](https://github.com/bounswe/bounswe2023group7/wiki/Mock-Ups).

**Comment by senaal** [comment]
I sent a request to be able to see the mock-ups in Figma, but I already saw them in Discord channel so I am closing that issue.
