### ISSUE TITLE
Adding Recommendation to Sequence Diagram

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#261]
### Issue Description

We need to update our sequence diagrams considering the feedbacks were given to us. Thus I will be creating a new sequence diagram to visualize recommendation action as assigned in the [ lab report.](https://github.com/bounswe/bounswe2023group7/blob/main/reports/lab_report_3.md)

### Tasks

Parts of the task:
- [x] Review use-case diagram for recommendation
- [x] Review class diagram to determine other components related to  recommendation
- [x] Create a sequence diagram for recommendation action

### Extra Comments

None

### Final Step

After finishing the task, I will review all design deliverables to check whether my newly created sequence diagram is compatible with overall project design.

### Deadline of the Issue

23.10.2023 - Monday - 23:59

### Reviewer

@mtkamiloglu

### Deadline for the Review

24.10.2023 - Tuesday - 16:00

**Comment by frknlke** [comment]
I reviewed our use-case diagrams and class diagrams to determine active component during recommendation action. Then I created a sequence diagram for recommendation action. Finally, I upload my sequence to [Sequence Diagrams](https://github.com/bounswe/bounswe2023group7/wiki/Sequence-Diagrams) page. Review is needed before closing the issue.
