### ISSUE TITLE
Revision of Meeting Notes Template

### ISSUE THREAD

**Issue by Hakkush-07** [bounswe/bounswe2023group7#27]
### Issue Description

We need to change the meeting notes template.

### Tasks

Parts of the task:
- [x] convert participants list to checkbox
- [x] change bullet points to enumeration
- [x] add "issue" column to action table

### Final Step

Notes of the meeting 3 will be added following this template

### Deadline of the Issue

18.03.2023

### Reviewer

@senaal

### Deadline for the Review

19.03.2023

**Comment by senaal** [comment]
Review is completed and I am closing the issue.
