### ISSUE TITLE
Adding Annotation to Sequence Diagram

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#276]
### Issue Description

I will create a new sequence diagram for annotation. 

### Tasks

Parts of the task:
- [ ] Reviewing other sequence diagrams for reference.
- [ ] Deciding on the processes or objects related to annotation.
- [ ] Design a sequence diagram for annotation.

### Deadline of the Issue

24.10.2023 - Tuesday - 11.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

24.10.2023 - Tuesday - 13.00

**Comment by kardelenerdal** [comment]
I created create, edit and delete annotation sequence diagrams. It can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/Sequence-Diagrams). I am not sure whether the admin should check the content of the annotation and approve it. If he/she should, I can change it accordingly.

**Comment by yunusemrealtug** [comment]
You can extend the timeline up under database to include actions. That does not seem much problematic, but I suggest you to modify it. We did not specify admin check for annotation. Therefore no problem on this. Thanks for the work. Closed
