### ISSUE TITLE
Implementing login and signup endpoints

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#283]
### Issue Description

A signup endpoint and a login endpoint will be created. The signup endpoint will create a user and return an access token to the client. The login endpoint will check the credentials and return an access token to the client.

### Tasks

Parts of the task:
- [x] Creating signup endpoint
- [x] Creating login endpoint
- [x] Creating unit tests for signup endpoint
- [x] Creating unit tests for login endpoint

### Deadline of the Issue

23.10.2023-23.59

### Reviewer

@omersafakbebek 

### Deadline for the Review

24.10.2023-15.00

**Comment by omersafakbebek** [comment]
I created the endpoints, wrote unit tests and swagger documentations for them. The issue can be closed after the linked pr is merged.

**Comment by omersafakbebek** [comment]
The pr has been merged.
