### ISSUE TITLE
Revision of Implementation of Mobil Home Page

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#301]
### Issue Description

The mobile page of the home page should be revised and updated with the color palette we decided.

### Tasks

Parts of the task:
- [x] The color of the home screen should be updated.
- [x] The project logo should be added.
- [x] The navigation bar should be updated.

### Deadline of the Issue

27 October 2023 - Friday - 5pm

### Reviewer

@kardelenerdal 

### Deadline for the Review

27 October 2023 - Friday - 11pm

**Comment by kardelenerdal** [comment]
Home page revision is done and merged. Issue can be closed.
