### ISSUE TITLE
Preparation of Presentation Scenerio

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#305]
### Issue Description

For the customer milestone presentation, we need to prepare scenarios to show the current state of the project.

### Tasks

Parts of the task:
- [x] Organize a meeting for the preparation.
- [x] Discuss the scenarios.
- [x] Prepare the presentation.

### Deadline of the Issue

29 October 2023 - Friday - 5pm

### Reviewer

@melihgezerr 

### Deadline for the Review

29 October 2023 - Friday - 11pm

**Comment by elifkizilky** [comment]
We met face to face and create a user scenario and presentation for our pre-release software. We shared our scenario with the rest of the group. The issue needs to be reviewed.
