### ISSUE TITLE
Preparation Milestone Report

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#308]
### Issue Description

We will prepare a milestone report for our first milestone. According to description, milestone report should follow this content:

- A summary of the project status and any changes that are planned for moving forward.
- A summary of the customer feedback and reflections.
- List and status of deliverables.
- Evaluation of the status of deliverables and its impact on your project plan (reflection).
- Evaluation of tools and processes you have used to manage your team project.
- The requirements addressed in this milestone.
- Individual contributions.

### Tasks

Parts of the task:
- [x] Write a summary of the project status and any changes that are planned for moving forward.
- [x] Write a summary of the customer feedback and reflections.
- [x] Write a list and status of deliverables.
- [x] Write an evaluation of the status of deliverables and its impact on your project plan (reflection).
- [x] Write an evaluation of tools and processes you have used to manage your team project.
- [x] Write the requirements addressed in this milestone.
- [x] Individual contributions.

### Deadline of the Issue

03.11.2023 21.00

### Reviewer

@haticerk 

### Deadline for the Review

03.11.2023 22.00

**Comment by elifkizilky** [comment]
The milestone report is prepared and delivered. The issue needs to be reviewed @haticerk.

**Comment by haticerk** [comment]
All the related issues are done. Nice team work!
