### ISSUE TITLE
Formalizing the Requirements According to SRS

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#31]
### Issue Description

We talked about our requirements in the last weeks. This week, we are going to formalize them according to the type of requirements that we learned in the lecture by utilizing SRS. These types are:
1. Functional Requirements
1.1. User Requirements
1.2. System Requirements
2. Non-functional Requirements

### Tasks

Parts of the task:
- [x] Open a Draft Requirements Page According to SRS
- [x] Title page section part
- [x] Revision history part
- [x] Fill Introduction part
- [x] Fill Functional Requirements Section
- [x] Fill Non-Functional Requirements Section
- [x] Fill Appendix part

### Extra Comments

We divided the task into subtasks by assigning the team members to each part. Please open another issue by mentioning this issue. 

### Final Step

Please check and tick the tasks when you complete them.

### Deadline of the Issue

20.03.2023 - 23.59

### Reviewer

@elifkizilky 

### Deadline for the Review

21.03.2023 - 23.59

**Comment by elifkizilky** [comment]
Our requirements are done according to the SRS model and can be accessed from [here](https://github.com/bounswe/bounswe2023group7/wiki/Requirements). Revision history can be seen under the headline "Requirements". We enumerate items for easy access.
