### ISSUE TITLE
Implementing Game Page for Ludos Web

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#317]
### Issue Description

I will implement the game page of Ludos. These page will have the features of the game. There page also will link the entities of the game.

### Tasks

Parts of the task:
- [x] Getting and representing real or mock data.
- [ ] Designing the the reviews.
- [ ] Linking other features.
- [ ] Designing the tabs
- [x] Designing the game image and short information container

### Extra Comments

This task is one of the most complex parts of the project. Aim of this task is representing a game page for presentation. Some parts may be revised, some parts will be needed to add. If something lacks, i may continue from different components of this page in future weeks.

### Deadline of the Issue

30.10.2023 - Monday - 16.59

### Reviewer

@mtkamiloglu 

### Deadline for the Review

30.10.2023 - Monday - 23.59

**Comment by yunusemrealtug** [comment]
In the other branch, I initialized also it so added this issue to pr, after merging this issue also closed due to linking. I am reopening it.
