### ISSUE TITLE
Implementation of Forget Password Page

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#320]
### Issue Description

I will implement the forgot password page and connect it to the login page. 

### Tasks

Parts of the task:
- [ ] Design the forgot password page 
- [ ] Implement the page

### Deadline of the Issue

31.10.2023 - Tuesday - 12.00

### Reviewer

@elifkizilky 

### Deadline for the Review

31.10.2023 - Tuesday - 15.00

**Comment by mtkamiloglu** [comment]
I designed and implemented the page. You can reach the forgot password page from login page. After clicking the link on login page it will look like this:
<img width="1679" alt="Ekran Resmi 2023-11-10 01 20 27" src="https://github.com/bounswe/bounswe2023group7/assets/70536420/30013658-d9a5-450c-b31e-8814a7e0f093">
When user entered her email, a code will be sent to her mailbox. She will write the code and after her new email. She will enter it to a popup:
<img width="1680" alt="Ekran Resmi 2023-11-10 01 23 35" src="https://github.com/bounswe/bounswe2023group7/assets/70536420/9eda3f0e-0adb-4514-81ac-11b10b8726da">
If she enters the correct code, page will navigate to the login page. Else, error navbar will be shown.
It can be reivewed @elifkizilky

**Comment by elifkizilky** [comment]
I tested the code and it worked smoothly. Here is what I have done:

- [x] Created a user with my credentials and logged in
- [x] After logged out, I clicked forgot password and it navigated me to the related page
- [x] I typed my email and it sent me code to my email
- [x] After entering the code, it changed my password
- [x] I entered with my new password


Thank you for your time. Issue can be closed.
