### ISSUE TITLE
Creating followGame Endpoint	

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#321]
### Issue Description

I will create an endpoint that is used for following the games. Then, unit tests and swagger documentation of the endpoint will be created.

### Tasks

Parts of the task:
- [x] Creating the endpoint
- [ ] Writing the unit tests for the endpoint
- [x] Writing the swagger documentation for the endpoint

### Deadline of the Issue

30.10.2023

### Reviewer

@Hakkush-07 

### Deadline for the Review

30.10.2023

**Comment by omersafakbebek** [comment]
I am reopening this issue for tests
