### ISSUE TITLE
Adding ESlint and Prettier 

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#332]
### Issue Description

In order to improve the code quality and maintainability of our React project, we can integrate ESLint and Prettier. These tools will enforce coding standards, catch potential issues, and ensure consistent code formatting. By implementing them, we can enhance the efficiency and collaboration within our development process.

### Tasks

Parts of the task:
- [ ] Configure ESLint with a customized configuration that aligns with our coding standards.
- [ ]  Integrate Prettier for automatic code formatting with a consistent style guide.
- [ ]  Set up .prettierignore file to exclude unnecessary directories and files from linting and formatting.
- [ ]  Add scripts to run ESLint and Prettier checks as part of our development workflow.

### Deadline of the Issue

30.10.23 - 21.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

30.10.23 - 23.59

**Comment by yunusemrealtug** [comment]
Something has problems there, tests are failed, I am reopening this. We should think about it.

**Comment by yunusemrealtug** [comment]
The problem is not related with this pr actually, but remote server must started again. Closed
