### ISSUE TITLE
Creating ChangePassword Endpoint

### ISSUE THREAD

**Issue by tacettinburakeren** [bounswe/bounswe2023group7#340]
### Issue Description

ı will create an endpoint for users to change their passwords. Then, unit tests and swagger documentation of the endpoint will be created.

### Tasks

Parts of the task:
- [ ] Creating the endpoint
- [ ] Writing the unit tests for the endpoint
- [ ] Writing the swagger documentation for the endpoint

### Deadline of the Issue

30.10.2023

### Reviewer

@omersafakbebek 

### Deadline for the Review

30.10.2023
