### ISSUE TITLE
Creating .apk for mobile application and updating ReadMe.md

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#365]
### Issue Description

We need to build and publish .apk file for Milestone 1.  The ReadMe.md should include how to build and run our mobile application.

### Tasks

Parts of the task:
- [x] Creating .apk file.
- [x] Add it to release.
- [x] Updating ReadMe.md

### Final Step

After publishing .apk file, we need to try it on an Android phone.

### Deadline of the Issue

31.10.2023 - Tuesday - 23.00

### Reviewer

@frknlke 

### Deadline for the Review

31.10.2023 - Tuesday - 23.30

**Comment by haticerk** [comment]
We have created the .apk file and added the download link to the README.md in the mobile folder. Also, we have added the instructions to the README.md. The PR is #368.

**Comment by haticerk** [comment]
The .apk was added to the pre-release version. The issue can be closed after review.

**Comment by frknlke** [comment]
All subtask were completed. Issue will be closed.
