### ISSUE TITLE
Revision of Software Design (UML Diagrams)

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#376]
### Issue Description

As part of our ongoing software development project, we have created a set of UML (Unified Modeling Language) diagrams to represent the design of our software system.  To ensure that the UML diagrams are of the highest quality and effectively communicate the design, we are going to revise them for the last time before delivering.

### Tasks

Parts of the task:
- [x] Revise use case diagrams
- [x] Revise class diagrams
- [x] Revise sequence diagrams

### Deadline of the Issue

02.11.23 23.59

### Reviewer

@kardelenerdal 

### Deadline for the Review

03.11.2023 15.00

**Comment by haticerk** [comment]
I have revised the UML diagrams for the last time. In my opinion, everything looks correct and related to the project. I also checked the links in the milestone report if they are correct or not.

**Comment by frknlke** [comment]
I also checked the UML diagrams. Both last year's work and this year's corrections look fine. Issue can be closed after review.

**Comment by kardelenerdal** [comment]
UML Diagrams are accessible from the milestone report and they look fine. Thank you. Issue can be closed.
