### ISSUE TITLE
Meeting Notes #3

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#381]
### Issue Description

We held a meeting for the design of our visuals on the web and mobile with @kardelenerdal , @mtkamiloglu , @haticerk . I'm going to write a meeting notes for it. 

### Tasks

Parts of the task:
- [x] Write meeting notes
- [x] Add it to wiki side bar
- [x] Add it to wiki home page

### Deadline of the Issue

03.11.23 12.00

### Reviewer

@frknlke 

### Deadline for the Review

03.11.2023 15.00

**Comment by elifkizilky** [comment]
I wrote the meeting notes 3 and added it to wiki sidebar and home page. The work can be accessed by this [link](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%233-23.10.23). The issue needs to be reviewed.
