### ISSUE TITLE
List and Status of Deliverables

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#400]
### Issue Description

For milestone report, I will create a list about deliverables. Also I will explain their status and I will add a brief information about deliverable. 

### Tasks

Parts of the task:
- [x] Create deliverables table.
- [x] Write their status and descriptions.
- [x] Add it to the milestone report.

### Deadline of the Issue

03.11.2023

### Reviewer

@kardelenerdal 

### Deadline for the Review

03.11.2023

**Comment by senaal** [comment]
The issue needs review, it can be seen from the template in our group.

**Comment by kardelenerdal** [comment]
I reviewed the List and Status of Deliverables in our template. It looks great. Thank you for your effort. One feedback is that it would be better if deliverables are linked to appropriate page in our Wiki as in previous year's groups.
