### ISSUE TITLE
Evaluation of Processes at the milestone 1 report

### ISSUE THREAD

**Issue by tacettinburakeren** [bounswe/bounswe2023group7#402]
### Issue Description

I contributed to the milestone 1 report by revising the evaluotion of processes in which I mentioned about the processes we have been through until now.

### Tasks

Parts of the task:
- [x] Evalution of processes(1)
- [x] Revising the ps&customer meetings (2)
- [x] Revising the team work processes (3)

### Deadline of the Issue

03.11.2023

### Reviewer

@mtkamiloglu 

### Deadline for the Review

03.11.2023

**Comment by mtkamiloglu** [comment]
I reviewed and am closing as completed.
