### ISSUE TITLE
Game Page Revision for Ludos Web

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#423]
### Issue Description

I will revise the game page. It has many components inside, so I think it was ready for the milestone presentation. However some design changes may be done.  Also I will connect it to backend.

### Tasks

Parts of the task:
- [x] Replacing mock data with backend data.
- [x] Design changes in game information table.
- [x] Implementation of nested tab structure.
- [ ] Adding genre to game page (not certain)

### Extra Comments

We plan to link whenever each part is implemented in backend to game page in each week.

### Deadline of the Issue

14.11.2023 - Tuesday - 00:00

### Reviewer

@elifkizilky 

### Deadline for the Review

14.11.2023 - Tuesday - 15:00
