### ISSUE TITLE
Creating list games endpoint

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#425]
### Issue Description

I will create an endpoint that lists the game. The endpoint will filter the games by their fields and search the games by name.

### Tasks

Parts of the task:
- [x] Creating the endpoint
- [x] Creating unit tests for the endpoint function
- [x] Creating the swagger documentation for the endpoint 

### Deadline of the Issue

14.11.2023

### Reviewer

@melihgezerr 

### Deadline for the Review

14.11.2023

**Comment by omersafakbebek** [comment]
I completed the tasks for the issue. My work can be reviewed [here](https://github.com/bounswe/bounswe2023group7/pull/445)
