### ISSUE TITLE
Header Revision

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#429]
### Issue Description

During the milestone demo, we identified deficiencies in the header such as "My Games" and "My Groups" sections of our application. To enhance the user experience and address these issues, we need to conduct a review and make necessary design changes to these sections.

### Tasks

Parts of the task:
- [x] Add "My Games" section
- [x] Add "My Groups" section
- [x] Identify and fix other deficient points

### Deadline of the Issue

14.11.2023 21.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

14.11.2023 23.59

**Comment by elifkizilky** [comment]
I completed the task and created the pull request. I connect this issue to the PR, when the PR is approved and merged, this issue will be closed automatically.
