### ISSUE TITLE
Revision of create game page

### ISSUE THREAD

**Issue by kardelenerdal** [bounswe/bounswe2023group7#460]
### Issue Description

Create game page is implemented last week but after reviewing it with the team, we decided to divide this page into 2 parts for a better user experience since there are too much fields in one page. Also, for some fields, I added a tag functionality and the user can add any string to that field. After the meeting, we decided that there should be static options for the user to choose. For example, for platforms, age information, etc.

### Tasks

Parts of the task:
- [x] Dividing the page into 2 or more.
- [x] Changing the mandatory fields.
- [x] Options for "Platforms" and "Age Restriction".
- [x] Updating the release date field.

### Deadline of the Issue

21.11.2023 - Tuesday - 12.00

### Reviewer

@haticerk 

### Deadline for the Review

21.11.2023 - Tuesday - 17.00
