### ISSUE TITLE
Revision of Game Page

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#467]
### Issue Description

The game pages in the mobile will be revised and implemented for all games. 

### Tasks

Parts of the task:
- [x] Revision of game page according to style.
- [x] Implement it to backend. 
- [x] Make it accessible from the games page.

### Deadline of the Issue

21.11.2023

### Reviewer

@frknlke 

### Deadline for the Review

21.11.2023

**Comment by senaal** [comment]
The task is completed, pr can be seen here #496

**Comment by frknlke** [comment]
All subtasks are completed and also PR successfully merged. Issue will be closed.
