### ISSUE TITLE
Creating Game Page After Submitting the Create-Game-Page Forum

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#472]
### Issue Description

After submitting the "Create Game" form, the application should redirect users to a dedicated page for the newly created game. Currently, upon successful submission of game details via the "Create Game" form, there is no redirect or creation of a specific game page.

### Tasks

Parts of the task:
- [x] Implement the functionality to redirect users to a dynamically generated game page after successfully submitting the "Create Game" form.
- [x] Populate the game page with the information entered in the form.
- [x] Test the navigation to the game page upon form submission.

### Deadline of the Issue

21.11.2023 21.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

21.11.2023 23.59

**Comment by elifkizilky** [comment]
I implemented the necessary task steps and created the pull request. I connected it to this issue so that when PR is merged, this issue can be closed.
