### ISSUE TITLE
Adding Post Feature to Backend

### ISSUE THREAD

**Issue by omersafakbebek** [bounswe/bounswe2023group7#477]
### Issue Description

For this issue, I will create a post entity. After that, I will create crud operations for the entity. Also, like and dislike functionalities will be added.

### Tasks

Parts of the task:
- [x] Creating the entity
- [x] Creating the crud endpoints
- [x] Creating like and dislike endpoints
- [x] Creating swagger documentation for the endpoints
- [ ] Creating unit tests for the endpoint

### Deadline of the Issue

21.11.2023

### Reviewer

@melihgezerr 

### Deadline for the Review

21.11.2023

**Comment by omersafakbebek** [comment]
The isse needs review. Unit tests will be created later.

**Comment by melihgezerr** [comment]
it looks well, great job
