### ISSUE TITLE
Login and Signup Show/Hide Password Feature

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#506]
### Issue Description

In login and signup page password cannot be seen by user. This will make to choose correct password hard for user. I will add showing and hiding feature to the these pages. 

### Tasks

Parts of the task:
- [x] Add show/hide feature to signup page
- [x] Add show/hide feature to login page
- [x] Add show/hide feature to change password page
- [x] Add show/hide feature to forgot password page

### Deadline of the Issue

27.11.2023 - Monday - 22.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

27.11.2023 - Monday - 23.00

**Comment by mtkamiloglu** [comment]
I added password visibility toggle to all these four pages. It looks like this in login page:
<img width="621" alt="Ekran Resmi 2023-11-25 02 14 18" src="https://github.com/bounswe/bounswe2023group7/assets/70536420/5defb317-2552-43b4-aa4c-fe95dab13fff">
I used very same components for the other pages also.
