### ISSUE TITLE
Create Post Page Revision and Backend Connection

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#507]
### Issue Description

I implemented the create post page but I couldn't connect it to backend because it was not ready. I also changed name 'Post' to 'Tread' and will make minor improvements.

### Tasks

Parts of the task:
- [x] Connect the page to backend. 
- [x] Change Post to Thread.
- [x] Make visual improvements.

### Deadline of the Issue

27.11.2023 - Monday - 22.00

### Reviewer

@elifkizilky 

### Deadline for the Review

27.11.2023 - Monday - 23.00

**Comment by mtkamiloglu** [comment]
I opened the pr for this issue. It can be seen from the left sidebar or from [here](https://github.com/bounswe/bounswe2023group7/pull/497). When the pr is merged this issue will be closed automatically.
