### ISSUE TITLE
Profile Page Adjustments

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#508]
### Issue Description

There was lack of backend features in backend, this will be added in  this week and should be reflected to the profile page. Also there should adjustment of profile page for external user and the owner of profile. 

### Tasks

Parts of the task:
- [ ] Adjusting profile page based on ownership of profile.
- [ ] Adding lack of backend features to profile page
- [ ] Design changes (not certain)

### Deadline of the Issue

27.11.2023 - Monday - 23.59

### Reviewer

@elifkizilky 

### Deadline for the Review

28.11.2023 - Tuesday - 11.59
