### ISSUE TITLE
Preparation of User Scenario for Milestone 2

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#509]
### Issue Description

For the customer milestone presentation, we need to prepare scenarios to show the current state of the project.

### Tasks

Parts of the task:
- [x]  Organize a meeting for the preparation.
- [x]  Discuss the scenarios.
- [x]  Prepare the presentation.

### Deadline of the Issue

26.11.2023 21.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

26.11.2023 23.59

**Comment by elifkizilky** [comment]
We met on 23.11.2023 at the CMPE lounge to discuss our user scenario. The scenario and the presentation slides are prepared and shared with the group through the Discord channel. This issue needs to be reviewed.

**Comment by kardelenerdal** [comment]
The meeting notes can be found [here](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%236-23.11.2023).

**Comment by yunusemrealtug** [comment]
The scenerio is really interesting. I hope it will work in the class for us :). Closing.
