### ISSUE TITLE
Search in the games

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#530]
### Issue Description

We need to implement search mechanism for games. I will use backend API's endpoints to form functionality of searching based on keys.

### Tasks

Parts of the task:
- [x] Form Search Page
- [x] Create UI structures for searching
- [x] Connect to Backend API
- [x] Create structure to view returned objects(games)

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

28.11.2023-Tuesday-10:00

### Reviewer

@kardelenerdal

### Deadline for the Review

28.11.2023-Tuesday-13:00

**Comment by frknlke** [comment]
I completed all subtask. [PR](https://github.com/bounswe/bounswe2023group7/pull/602) opened and after successfully merging into development branch, issue will be closed.
