### ISSUE TITLE
Create Data for the Platform

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#534]
### Issue Description

We need to create some data for the platform to present in the customer presentation and help in testing. For the issue, everyone should create:

- A game
- Two reviews for that game
- Two or three threads for that game
- One or two comments to these threads

Also, we need to create with a users whose username is not random.  

### Tasks

Parts of the task:
- [x] Burak Eren
- [x] Elif Kızılkaya
- [x] Fatma Sena Alçı
- [x] Furkan Ülke 
- [x] Hakan Karakuş
- [x] Hatice Erk
- [x] Kardelen Erdal 
- [x] Melih Gezer
- [x] Muhammet Tayyip Kamiloğlu
- [x] Ömer Şafak Bebek
- [x] Yunus Emre Altuğ 

### Deadline of the Issue

26 November 2023 -  Sunday - 11pm

### Reviewer

@haticerk

### Deadline for the Review

27 November 2023 -  Monday - 11pm

**Comment by elifkizilky** [comment]
Witcher 3 and sims 4 games should be created. They are mentioned in the home page

**Comment by elifkizilky** [comment]
The data is created and our demo went smoothly. Thank you everyone for your effort and time. I'm closing this issue.
