### ISSUE TITLE
Use Case Diagram - Group Finding

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#55]
### Issue Description

As we discussed in Meeting 5, use case diagrams should be created. One of the parts that should be represented in the daigram is group finding feature.

### Tasks

Parts of the task:
- [x] Determine for which category of user(s) group finding action can be performed.
- [x] Create use case(s) for related goals.
- [x] Structure the use cases.

### Extra Comments

Checking information at this [link](https://creately.com/guides/use-case-diagram-tutorial/) can provide a good foundation of how to create class diagrams.

### Final Step

After finishing this task, I will create class diagram for Group as [planned.](https://github.com/bounswe/bounswe2023group7/issues/56)

### Deadline of the Issue

03.04.2023 - Monday - 12:00

### Reviewer

@SouthAscend

### Deadline for the Review

03.04.2023 - Monday - 23:59

**Comment by frknlke** [comment]
I completed my part in use - case diagram. I added manage group, create group, search group, and manage membership in the group sub-use cases. After other parts completed, final diagram will be added to [corresponding page](https://github.com/bounswe/bounswe2023group7/wiki/Use-Case-Diagrams).

**Comment by frknlke** [comment]
For now the parts I did can be seen below:

![Use case diagram](https://user-images.githubusercontent.com/61520034/229634771-08efd803-5fff-471e-8940-e35c6393aeab.png)

![Opera Anlık Görüntü_2023-04-04_004108_lucid app](https://user-images.githubusercontent.com/61520034/229634852-bbf1d343-6f9c-4e74-aaa7-958e18ba5427.png)

![Opera Anlık Görüntü_2023-04-04_004133_lucid app](https://user-images.githubusercontent.com/61520034/229634952-7c4acac5-af04-4131-920e-7fa22718668a.png)

![Opera Anlık Görüntü_2023-04-04_004206_lucid app](https://user-images.githubusercontent.com/61520034/229635003-fa9a9b4b-e25f-44ea-a1c7-0c03cf38d60c.png)

![Opera Anlık Görüntü_2023-04-04_004245_lucid app](https://user-images.githubusercontent.com/61520034/229635024-323fb3c4-8dd3-4b94-adb2-6ccb78ff7655.png)
