### ISSUE TITLE
Adding Comments to the Threads

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#570]
### Issue Description

We need to add comments to the threads, and comments again. 

### Tasks

Parts of the task:
- [ ] Navigate the comment buttons to create a comment.
- [ ] Implement the comment functionality.
- [ ] List the comments of a thread on its own page.

### Deadline of the Issue

26 November 2023 -  Sunday - 11pm

### Reviewer

@kardelenerdal 

### Deadline for the Review

27 November 2023 -  Monday - 8pm
