### ISSUE TITLE
Meeting 5 Notes

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#59]
### Issue Description

Meeting 5 is held on 30.03.2023. As a note-taker, I will create meeting page and share the notes.

### Tasks

Parts of the task:
- [x]  Create the page.
- [x] Add meeting notes.
- [x] Add page to the sidebar.

### Deadline of the Issue

02.01.2023 - Monday - 23.59

### Reviewer

@elifkizilky

### Deadline for the Review

02.01.2023 - Monday - 23.59

**Comment by mtkamiloglu** [comment]
I created the Meeting 5 [page](https://github.com/bounswe/bounswe2023group7/wiki/Meeting-%235-(30.03.2023)). After creating issues for their task, people can edit this page and add their issue link to the table and update their deadline.

**Comment by mtkamiloglu** [comment]
Meeting #5 page is added to the sidebar. Issue can be reviewed.

**Comment by elifkizilky** [comment]
I'm closing this issue since it is completed.
