### ISSUE TITLE
Creating main search page for the mobile app

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#643]
### Issue Description

Currently, we made search for games and users in different pages. I will create a main search page that allows user to restrict result as they desired. I will open additional issues that will be sub-tasks of this issue

### Tasks

Parts of the task:
- [x] Create search page layout
- [x] Add filter button
- [x] Add sorting criteria if backend API service supports it
- [x] Connect necessary contents to backend API

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

12.12.2023 - Tuesday - 12:00

### Deadline for the Review

12.12.2023 - Tuesday - 15:00

**Comment by frknlke** [comment]
I implemented search for game and search for user parts. Now only Search for Posts remained. I will complete it also as soon as possible.
