### ISSUE TITLE
Edit/Delete Review, Thread and Comment

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#647]
### Issue Description

The edit and delete features of review, thread, and comment should be added.

### Tasks

Parts of the task:
- [x] Edit/delete of comment
- [x] Edit/delete of thread
- [ ] Edit/delete of review

### Deadline of the Issue

12 December 2023 - Tuesday - 3pm

### Reviewer

@kardelenerdal 

### Deadline for the Review

12 December 2023 - Tuesday - 5pm

**Comment by haticerk** [comment]
The comment and thread parts are done within #672.

**Comment by haticerk** [comment]
Edit/delete of review issue will continue under #695. This issue can be closed after the review.
