### ISSUE TITLE
Filter and Sort features in Search

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#649]
### Issue Description

I will add filter and search features to the games search and forum search.

### Tasks

Parts of the task:
- [x] Filter feature of games search
- [x] Sort feature of games search
- [ ] Filter feature of forums search
- [ ] Sort feature of forums search

### Deadline of the Issue

12.12.2023 - Tuesday - 12.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

12.12.2023 - Tuesday - 15.00

**Comment by mtkamiloglu** [comment]
In the frontend, the filter and sort in the search required more discussion so the task will be completed in the following week after the discussion in the lab with the other complementary features in the search such as general search bar in the header.
