### ISSUE TITLE
Coverting BottomNavigationBar to a reusable widget

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#664]
### Issue Description

Currently we are using built-in navigationBar widget. It forces as to redeclare the widget with all its parameters again and again. I will create a custom widget so that whenever we plan to make changes on bottom navigation bar , changing only widget's itself will be sufficient rather than changing all the occurrences of it.

### Tasks

Parts of the task:
- [ ] Form a reusable widget for BottomNavigationBar
- [ ] Replace it with the current occurrences of built-in widget
- [ ] Test its functionality

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

08.12.2023 - Friday - 13:00

### Reviewer

@haticerk

### Deadline for the Review

08.12.2023 - Friday - 15:00
