### ISSUE TITLE
Main Search Page - Search for a Game

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#667]
### Issue Description

As I mentioned in the [main issue](https://github.com/bounswe/bounswe2023group7/issues/643), search page for mobile app should be implemented. Games also will be able to search by users in this page

### Tasks

Parts of the task:
- [ ] Create layout for selecting search for game
- [ ] Connect necessary mechanisms to backend api
- [ ] Create layout for listing search results

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

12.12.2023 - Tuesday - 12:00

### Deadline for the Review

12.12.2023 - Tuesday - 15:00
