### ISSUE TITLE
Forum Revision 

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2023group7#696]
### Issue Description

The forum page needs some revision. 

### Tasks

Parts of the task:
- [x] Put the profile picture of the user in the threads and comments.
- [ ] Work on mentioning the users.
- [x] Add the number of comments of comments

### Deadline of the Issue

19 December 2023 - Tuesday - 3pm

### Reviewer

@frknlke 

### Deadline for the Review

19 December 2023 - Tuesday - 5pm
