### ISSUE TITLE
Game Topic Implementation

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#702]
### Issue Description

I will create a component for games like a preview. It will have fields about games and when a user click it will lead to the game page. I will use this component in both related games tab and suggested games in games page.

### Tasks

Parts of the task:
- [x] Create the component
- [x] Use it on game page (related games)
- [x] Use it on games page (suggested games)

### Deadline of the Issue

19.12.2023 - Tuesday - 12.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

19.12.2023 - Tuesday - 15.00

**Comment by mtkamiloglu** [comment]
I created the component. In this component user can see these:
- game name
- game developer
- release date
- cover of the game
- game bio
- average rate
- tags

It looks as below:
<img width="685" alt="Ekran Resmi 2023-12-14 20 31 50" src="https://github.com/bounswe/bounswe2023group7/assets/70536420/6be414b3-799a-4747-9fa2-d80167277add">
If you have any feedbacks I can consider them

**Comment by mtkamiloglu** [comment]
I added this component to related games tabs:
<img width="890" alt="Ekran Resmi 2023-12-16 03 29 43" src="https://github.com/bounswe/bounswe2023group7/assets/70536420/72b1a095-e990-46e3-a239-a50f6b52bd63">
I also added to Games Page:
<img width="1224" alt="Ekran Resmi 2023-12-16 03 30 39" src="https://github.com/bounswe/bounswe2023group7/assets/70536420/1fc75d12-0d80-4a3f-ad0d-5b0e5dd3f63b">

issue can be reviewed @yunusemrealtug
