### ISSUE TITLE
File Upload Functionality

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#705]
### Issue Description

I will add file upload feature in create game, create entity, create thread.

### Tasks

Parts of the task:
- [ ] File upload in create game
- [ ] File upload in create entity
- [ ]  File upload in create thread

### Deadline of the Issue

19.12.2023

### Reviewer

@frknlke

### Deadline for the Review

19.12.2023

**Comment by senaal** [comment]
The task is blocked after discussions.
