### ISSUE TITLE
Profile page revision for my groups/favorite genre/tag/user type

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#713]
### Issue Description

The profile page needs to be revised to adapt to new features. The features to be added are written on the tasks part.

### Tasks

Parts of the task:
- [x] Add `My Groups` part to profile page
- [x] Discard favorite genre/ favorite tags of the user since they are not being used in the platform
- [x] User type field will be added: `gamer`, `developer`, `e-sport player`

### Deadline of the Issue

19.12.2023 21.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

19.12.2023 23.59

**Comment by elifkizilky** [comment]
I added them all only in the groups section of the profile page; it needs to be revised after the implementation of the group topic to display the groups the user is in.
