### ISSUE TITLE
Implementing upcoming titles component for frontend and integrating them to the website

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#714]
### Issue Description

We will add user types to our platform. As indicated in the requirements, developers should be able to add their upcoming titles to our platform. I will implement the upcoming title component. I will open a part in our platform to display these titles, I will make a design for it first.

### Tasks

Parts of the task:
- [ ] Implement upcoming title component
- [ ] Make a design for integrating it to platform (will it be in the forums page?, home page? etc.)
- [ ] Integrate it to platform
into

### Extra Comments

I will extend this issue's deadline since the backend should implement it first. Normally we set to 1 week after but this issue will take 2-3 extra days.

### Deadline of the Issue

22.12.2023 21.59

### Reviewer

@yunusemrealtug 

### Deadline for the Review

22.12.2023 23.59

**Comment by elifkizilky** [comment]
I made a design in Figma for upcoming titles. I'm waiting backend for implementing it.
I'm planning to put upcoming titles in the games page and home page.

**Comment by elifkizilky** [comment]
I still wait for the backend so I will extend the deadline for couple of days.
