### ISSUE TITLE
UI enhancements

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#727]
### Issue Description

While testing our UI in frontend, I found some enhancements for better UI/UX as mentioned below.

### Tasks

Parts of the task:
- [x] In the game page, entities section should be revised and connected to backend
- [x] In the game, create an entity button should be added
- [x] In the game page, in related games section, the precedessors and successors should be displayed in the game topics component

### Deadline of the Issue

-

**Comment by yunusemrealtug** [comment]
First two actually will be part of entity page revision. However the third has some problems. These type of features are not kept in database as a game, they are kept as string. Therefore, the game may not be in database, so loading it may not be possible as we desired.

**Comment by elifkizilky** [comment]
we can check if it exists in the database, if exists; we can add it with a game topic. At least, we can provide a link if the game exists in the database. Also, while creating the game; also creating its predecessors and successors would be better. 

We can do so for demonstrating purposes in the final milestone.

**Comment by elifkizilky** [comment]
Also, in the entities section of the game page; they are just texts and even if they are clickable; they dont look like that :D We can wrap each entity in a topic where the image of it and the title are seen. What do you think?

**Comment by elifkizilky** [comment]
![image](https://github.com/bounswe/bounswe2023group7/assets/69367633/4b38d816-49db-4b6e-be64-611c716c46a8)


we can add some gaps between those in the groups page.
