### ISSUE TITLE
Last Activity section in the Mobile App

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#751]
### Issue Description

As we decided in [1.1.2.7. Activity Tracking](https://github.com/bounswe/bounswe2023group7/wiki/Requirements), users' last activities posts, threads etc will be showed in their profile pages. I will implement this feature for the mobile app.

### Tasks

Parts of the task:
- [ ] Implement mechanism to retrieve user's actions.
- [ ] Create workflow to sort retrieved activities.
- [ ] Create UI/UX structure to visualize results.

### Extra Comments

None

### Final Step

None

### Deadline of the Issue

26.12.2023 - Tuesday - 12:00

### Reviewer

@kardelenerdal 

### Deadline for the Review

26.12.2023 - Tuesday - 14:00
