### ISSUE TITLE
Implement annotation in Frontend

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#755]
### Issue Description

Annotation will be implement in the entity, game, and thread pages. The division between the tasks will be made.

### Tasks

Parts of the task:
- [x] Annotation in entity
- [x] Annotation in game
- [x] Annotation in thread

### Deadline of the Issue

25.12.23 15.00

### Reviewer

@elifkizilky @yunusemrealtug @mtkamiloglu 

### Deadline for the Review

25.12.23 18.00

**Comment by elifkizilky** [comment]
This can be closed as completed.
