### ISSUE TITLE
Sequence Diagram - Register & Login

### ISSUE THREAD

**Issue by elifkizilky** [bounswe/bounswe2023group7#77]
### Issue Description

Sequence diagrams for register & login will be made and added to the main sequence diagram.

### Tasks

Parts of the task:
- [x] Sequence diagram for register
- [x] Sequence diagram for login
- [x] Add to the main sequence diagram page

### Extra Comments

This [lin ](https://www.youtube.com/watch?v=pCK6prSq8aw) can be helpful for tasks.

### Deadline of the Issue

08.04.2023 17.00

### Reviewer

@frknlke 

### Deadline for the Review

09.04.2023 18.00

**Comment by elifkizilky** [comment]
Sequence diagrams for register & login can be seen below.
![Sequence diagram](https://user-images.githubusercontent.com/69367633/230724011-018f06ea-f421-4689-8b62-ef513007d6a8.jpeg)

The issue needs review.

**Comment by frknlke** [comment]
I did review the sequence diagrams and not encounter an error. I am closing the issue.
