### ISSUE TITLE
Remove Trending Games and Add Upcoming Titles

### ISSUE THREAD

**Issue by mtkamiloglu** [bounswe/bounswe2023group7#775]
### Issue Description

I will remove the trending games component from games page and add upcoming titles component instead. I will also create a component for the upcoming titles.

### Tasks

Parts of the task:
- [ ] Create a component for upcoming title
- [x] Remove trending games from games page
- [x] Add upcoming titles to the games page.

### Deadline of the Issue

24.12.2023 - Monday - 22.00

### Reviewer

@yunusemrealtug 

### Deadline for the Review

24.12.2023 - Monday - 24.00

**Comment by mtkamiloglu** [comment]
I added the component that is created by Elif to the games page. I removed trending games part and add there. I forgot to link the pr to this issue. Since pr [#823](https://github.com/bounswe/bounswe2023group7/pull/823) is merged I am closing this issue.
