### ISSUE TITLE
Preparing Project Plan Draft

### ISSUE THREAD

**Issue by senaal** [bounswe/bounswe2023group7#79]
### Issue Description

I will prepare project plan draft for documentation.

### Tasks

Parts of the task:
- [x] Analyzing Moodle document
- [x] Specifying what has been done so far
- [x] Preparing project plan draft according to these data

### Deadline of the Issue

07.04.2023

### Reviewer

@omersafakbebek 

### Deadline for the Review

08.04.2023

**Comment by senaal** [comment]
The draft for first milestone is created and it is published our private group.

**Comment by omersafakbebek** [comment]
The review has been completed. The task is done.

**Comment by senaal** [comment]
I made a mistake and prepared the milestone report draft instead of project plan draft.
