### ISSUE TITLE
Use Case Diagram Revision

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#83]
### Issue Description

We need to revise our use case diagram before the milestone report. I will revise group finding and annotation part.

### Tasks

Parts of the task:
- [x] Revise group finding use case
- [x] Revise annotation use case
- [x] Revise the relationships (include / extend) 

### Extra Comments

_No Response_

### Final Step

_No Response_

### Deadline of the Issue

08.04.2023 - Saturday - 18:00

### Reviewer

@elifkizilky

### Deadline for the Review

09.04.2023 - Sunday - 18:00

**Comment by frknlke** [comment]
I revised the group finding use case and made the following changes according to the revision in requirements:

1. Changing in search group use case - sort group subaction defined further. Added options for sorting regarding alphabetic, number of user, and number of empty slots constraints.
2. Relationship between manage group and edit group changed from include to extend.

Review is needed.

**Comment by elifkizilky** [comment]
The work is done and can be seen [here](https://github.com/bounswe/bounswe2023group7/wiki/Use-Case-Diagrams) once all the work is uploaded, also by this [link](https://lucid.app/lucidchart/b12a03f4-2573-4fb4-8788-1023b37b30d7/edit?viewport_loc=-1179%2C2368%2C2922%2C1395%2C.Q4MUjXso07N&invitationId=inv_64637227-de8d-40ce-ba52-63a136d4eece).
