### ISSUE TITLE
Sequence Diagrams - Group

### ISSUE THREAD

**Issue by frknlke** [bounswe/bounswe2023group7#85]
### Issue Description

We need to add sequence diagrams to our work. In this part, I will create sequence diagram(s) for group feature.

### Tasks

Parts of the task:
- [ ] Revisit project description to set main actions about group feature
- [ ] Revisit requirements page to decide whether there is some more actions about group that needs to showed on sequnce diagrams.
- [ ] Create issues about actions decided to include in diagram.

### Extra Comments

_No Response_

### Final Step

After I finishing this part, I will create issues for sequence diagrams and start to form diagrams.

### Deadline of the Issue

06.04.2023 - Thursday - 23:59

### Reviewer

@melihgezerr

### Deadline for the Review

08.04.2023 - Saturday - 18:00

**Comment by frknlke** [comment]
I have revisited both project description and requirements page. For now, sequence diagrams for create group and join group features are necessary. I will create issue for them. If some other features come out as necessity I will write them up here and create issues for them, too.

**Comment by frknlke** [comment]
There is no other suggestion for sequence diagrams about group action. Task is completed. Review is needed.
