### ISSUE TITLE
Class Diagram - Comment Class Structure

### ISSUE THREAD

**Issue by yunusemrealtug** [bounswe/bounswe2023group7#88]
### Issue Description

There should be sub-comment classes which inherite the comment class.  

### Tasks

Parts of the task:
- [x] Designing uml for review comments.
- [x] Designing uml for forum comments.
- [x] Designing comment parent class.
- [x] Determining inherited attributes.

### Deadline of the Issue

08.04.2023 - Saturday - 17.00

### Reviewer

@omersafakbebek 

### Deadline for the Review

09.04.2023 - Sunday - 18.00

**Comment by yunusemrealtug** [comment]
My work was based on comment subclasses' uml diagrams. They are connected also, review class, event class, and post class. You can see from here currently. Also review is needed now.
![UML class (1)](https://user-images.githubusercontent.com/100098311/230695906-84b1da49-62e3-4a29-baf6-c7aeb0f9bf29.png)

**Comment by omersafakbebek** [comment]
The review has been completed. The task is done.
